var namespace_ipertrade_1_1_booking_for_1_1_admin_1_1_modules_1_1bookingfor =
[
    [ "OTAServices", "namespace_ipertrade_1_1_booking_for_1_1_admin_1_1_modules_1_1bookingfor_1_1_o_t_a_services.html", "namespace_ipertrade_1_1_booking_for_1_1_admin_1_1_modules_1_1bookingfor_1_1_o_t_a_services" ],
    [ "Services", "namespace_ipertrade_1_1_booking_for_1_1_admin_1_1_modules_1_1bookingfor_1_1_services.html", "namespace_ipertrade_1_1_booking_for_1_1_admin_1_1_modules_1_1bookingfor_1_1_services" ]
];